apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: rust-autoscaler
  namespace: scale-namespace
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: rust-deployment
  minReplicas: 1 
  maxReplicas: 8
  behavior: 
    scaleDown:
      stabilizationWindowSeconds: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
