apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-deployment
  namespace: scale-namespace
  labels:
    app: rust-deploy
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: rust-pod
  template:
    metadata:
      labels:
        app: rust-pod
    spec:
      containers:
        - name: rust
          image: rust-demo:latest
          imagePullPolicy: IfNotPresent
          ports: 
            - containerPort: 8080
