apiVersion: v1
kind: Service
metadata:
  mame: rust-service
  namespace: scale-namespace
spec:
  type: NodePort
  selector:
    app: rust-pod
  ports: 
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001
