apiVersion: v1
kind: ConfigMap
metadata:
  name: datasources
  labels:
    name: datasources
  namespace: monitoring
data:
  prometheus.yaml: |-
    apiVersion: 1
    datasources:
      - name: prometheus
        type: prometheus
        acess: proxy
        isDefault: true
        url: http://prometheus.monitoring.svc:8080
